services:
  - type: web
    name: portfolio
    env: node
    buildCommand: node --max-old-space-size=2048 $(which npm) run install-deps && npm run build
    startCommand: node build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048 