services:
  - type: static
    name: portfolio
    buildCommand: npm install && npm run build
    publishDirectory: build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production 