services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && npm run build
    publishDirectory: build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production 